#pragma once

#include "resources/credits.xpm"
#include "resources/cursor.xpm"
#include "resources/game/draw.xpm"
#include "resources/game/one_wins.xpm"
#include "resources/game/player_one_hud.xpm"
#include "resources/game/player_two_hud.xpm"
#include "resources/game/two_wins.xpm"
#include "resources/high_scores/back.xpm"
#include "resources/high_scores/back_highlight.xpm"
#include "resources/high_scores/date.xpm"
#include "resources/high_scores/high_scores_title.xpm"
#include "resources/high_scores/name.xpm"
#include "resources/high_scores/rank.xpm"
#include "resources/high_scores/time.xpm"
#include "resources/high_scores/stripe.xpm"
#include "resources/high_scores/hs_background.xpm"
#include "resources/letters/a.xpm"
#include "resources/letters/b.xpm"
#include "resources/letters/c.xpm"
#include "resources/letters/d.xpm"
#include "resources/letters/e.xpm"
#include "resources/letters/f.xpm"
#include "resources/letters/g.xpm"
#include "resources/letters/h.xpm"
#include "resources/letters/i.xpm"
#include "resources/letters/j.xpm"
#include "resources/letters/k.xpm"
#include "resources/letters/l.xpm"
#include "resources/letters/m.xpm"
#include "resources/letters/n.xpm"
#include "resources/letters/o.xpm"
#include "resources/letters/p.xpm"
#include "resources/letters/q.xpm"
#include "resources/letters/r.xpm"
#include "resources/letters/s.xpm"
#include "resources/letters/t.xpm"
#include "resources/letters/u.xpm"
#include "resources/letters/v.xpm"
#include "resources/letters/w.xpm"
#include "resources/letters/x.xpm"
#include "resources/letters/y.xpm"
#include "resources/letters/z.xpm"
#include "resources/menu/background.xpm"
#include "resources/menu/exit.xpm"
#include "resources/menu/exit_highlight.xpm"
#include "resources/menu/high_scores.xpm"
#include "resources/menu/high_scores_highlight.xpm"
#include "resources/menu/local_highlight.xpm"
#include "resources/menu/local_mode.xpm"
#include "resources/menu/remote_highlight.xpm"
#include "resources/menu/remote_mode.xpm"
#include "resources/menu/title.xpm"
#include "resources/menu/times.xpm"
#include "resources/menu/Coin1.xpm"
#include "resources/menu/Coin2.xpm"
#include "resources/menu/Coin3.xpm"
#include "resources/menu/Coin4.xpm"
#include "resources/menu/Coin5.xpm"
#include "resources/menu/Coin6.xpm"
#include "resources/numbers/dots_big.xpm"
#include "resources/numbers/eight_big.xpm"
#include "resources/numbers/five_big.xpm"
#include "resources/numbers/four_big.xpm"
#include "resources/numbers/nine_big.xpm"
#include "resources/numbers/one_big.xpm"
#include "resources/numbers/one_small.xpm"
#include "resources/numbers/seven_big.xpm"
#include "resources/numbers/six_big.xpm"
#include "resources/numbers/ten_big.xpm"
#include "resources/numbers/three_big.xpm"
#include "resources/numbers/three_small.xpm"
#include "resources/numbers/two_big.xpm"
#include "resources/numbers/two_small.xpm"
#include "resources/numbers/zero_big.xpm"
#include "resources/numbers/zero_small.xpm"

static xpm_string_t *numbers[] = {zero_big_xpm, one_big_xpm, two_big_xpm, three_big_xpm, four_big_xpm, five_big_xpm, six_big_xpm, seven_big_xpm, eight_big_xpm, nine_big_xpm, ten_big_xpm};

static xpm_string_t *counters[] = {zero_small_xpm, one_small_xpm, two_small_xpm, three_small_xpm};

static xpm_string_t *wins[] = {draw_xpm, one_wins_xpm, two_wins_xpm};

static xpm_string_t *letters[] = {a_xpm, b_xpm, c_xpm, d_xpm, e_xpm, f_xpm, g_xpm, h_xpm, i_xpm, j_xpm, k_xpm, l_xpm, m_xpm, n_xpm, o_xpm, p_xpm, q_xpm, r_xpm, s_xpm, t_xpm, u_xpm, v_xpm, w_xpm, x_xpm, y_xpm, z_xpm};
